# compose file for building the test base images

services:
  tester-ubuntu-22.04:
    build:
      context: .
      args:
        UBUNTU_BASE: ubuntu:22.04
    pull_policy: never
    image: ghcr.io/tier4/ota-client/test_base:ubuntu_22.04

  tester-ubuntu-24.04:
    build:
      context: .
      args:
        UBUNTU_BASE: ubuntu:24.04
    pull_policy: never
    image: ghcr.io/tier4/ota-client/test_base:ubuntu_24.04
