name: push main

on:
  pull_request:
    branches:
      - main
      - test
    types: [closed]

jobs:
  update_version:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install packages
        run: >-
          python -m pip install -r proto/requirements.txt

      - name: protobuf build
        run: |
          cd proto
          make

      - name: update .proto_hash
        run: |
          cd proto
          proto_hash=$(python3 proto_hash.py)
          if [ ${proto_hash} != $(cat .proto_hash) ]; then
            echo ${proto_hash} > .proto_hash
            python3 increment_minor.py $(cat .version) > .version
          fi
          make clean

      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: update otaclient_pb2 hash and version
